-- with scrap as (
--     select *
--     from {{ ref('top_1000')}}
-- ),
-- convert_rate as (
--     select SCRAPED_NAME,
--     {{ percent_conversion('pell_grant_rate') }} AS pell_grant_rate,
--     {{ percent_conversion('admission_rate_overall') }} AS admission_rate_overall,
--     {{ percent_conversion('completion_rate_suppressed') }} AS completion_rate_suppressed,
--     {{ percent_conversion('retention_rate_full_time') }} AS retention_rate_full_time,
--     {{ percent_conversion('federal_loan_rate') }} AS federal_loan_rate,
--     {{ percent_conversion('student_demographics_men') }} AS student_demographics_men,
--     {{ percent_conversion('student_demographics_women') }} AS student_demographics_women,
--     {{ percent_conversion('faculty_demographics_men') }} AS faculty_demographics_men,
--     {{ percent_conversion('faculty_demographics_women') }} AS faculty_demographics_women
--     from scrap
-- )

-- select *
-- from convert_rate